// ============================================================================
// waki-themes / families.mjs
// ----------------------------------------------------------------------------
// Generated by scripts/gen-v2-themes.mjs.
// Material families define structure. Variants define hue/colorway.
// ============================================================================

export const FAMILIES = {
  "glass": {
    "name": "Waki Glass",
    "description": "Luminous translucent app chrome with crisp layered depth. Best for polished dashboards and creative tools.",
    "structure": {
      "radius": 14,
      "blur": 30,
      "shadow": "luminous-glass",
      "surface": "translucent",
      "iconography": "regular",
      "density": "comfortable"
    },
    "variants": [
      {
        "slot": "prism",
        "themeId": "waki-glass-prism",
        "name": "Prism",
        "description": "Indigo and teal glass for polished product dashboards.",
        "palette": {
          "light": {
            "bgFrom": "#f3f7fb",
            "bgTo": "#eef2f7",
            "panel": "rgba(255,255,255,.66)",
            "border": "rgba(79,70,229,.18)",
            "text": "#102033",
            "accent": "#4f46e5"
          },
          "dark": {
            "bgFrom": "#080d1c",
            "bgTo": "#111a2d",
            "panel": "rgba(79,70,229,.12)",
            "border": "rgba(94,234,212,.2)",
            "text": "#eef7ff",
            "accent": "#a5b4fc"
          }
        }
      },
      {
        "slot": "opal",
        "themeId": "waki-glass-opal",
        "name": "Opal",
        "description": "Teal and slate glass for calm operations tools.",
        "palette": {
          "light": {
            "bgFrom": "#f0faf8",
            "bgTo": "#f5f8fb",
            "panel": "rgba(255,255,255,.68)",
            "border": "rgba(15,118,110,.2)",
            "text": "#07333a",
            "accent": "#0f766e"
          },
          "dark": {
            "bgFrom": "#03191d",
            "bgTo": "#082832",
            "panel": "rgba(45,212,191,.1)",
            "border": "rgba(153,246,228,.2)",
            "text": "#dffcf8",
            "accent": "#5eead4"
          }
        }
      },
      {
        "slot": "civic",
        "themeId": "waki-glass-civic",
        "name": "Civic",
        "description": "Cobalt and amber glass for operational dashboards.",
        "palette": {
          "light": {
            "bgFrom": "#eef4ff",
            "bgTo": "#fff8ea",
            "panel": "rgba(255,255,255,.68)",
            "border": "rgba(37,99,235,.22)",
            "text": "#12213d",
            "accent": "#2563eb"
          },
          "dark": {
            "bgFrom": "#061329",
            "bgTo": "#24180a",
            "panel": "rgba(37,99,235,.14)",
            "border": "rgba(251,191,36,.26)",
            "text": "#edf4ff",
            "accent": "#60a5fa"
          }
        }
      },
      {
        "slot": "obsidian",
        "themeId": "waki-glass-obsidian",
        "name": "Obsidian",
        "description": "Charcoal glass with restrained ruby and copper accents.",
        "palette": {
          "light": {
            "bgFrom": "#f8f4f3",
            "bgTo": "#f6f7f9",
            "panel": "rgba(255,255,255,.72)",
            "border": "rgba(190,18,60,.18)",
            "text": "#221316",
            "accent": "#be123c"
          },
          "dark": {
            "bgFrom": "#050607",
            "bgTo": "#1c1210",
            "panel": "rgba(255,255,255,.07)",
            "border": "rgba(251,113,133,.22)",
            "text": "#fff3f2",
            "accent": "#fda4af"
          }
        }
      }
    ]
  },
  "frost": {
    "name": "Waki Frost",
    "description": "Soft high-blur frosted panes with misty depth and gentle hover shimmer.",
    "structure": {
      "radius": 16,
      "blur": 42,
      "shadow": "mist-depth",
      "surface": "frosted",
      "iconography": "regular",
      "density": "comfortable"
    },
    "variants": [
      {
        "slot": "arctic",
        "themeId": "waki-frost-arctic",
        "name": "Arctic",
        "description": "Blue-white frost for focused utility apps.",
        "palette": {
          "light": {
            "bgFrom": "#eef8ff",
            "bgTo": "#f8fcff",
            "panel": "rgba(255,255,255,.68)",
            "border": "rgba(14,165,233,.22)",
            "text": "#082f49",
            "accent": "#0284c7"
          },
          "dark": {
            "bgFrom": "#041623",
            "bgTo": "#082f49",
            "panel": "rgba(14,165,233,.14)",
            "border": "rgba(125,211,252,.28)",
            "text": "#e0f7ff",
            "accent": "#7dd3fc"
          }
        }
      },
      {
        "slot": "rose",
        "themeId": "waki-frost-rose",
        "name": "Rose",
        "description": "Muted rose frost for polished editorial workflows.",
        "palette": {
          "light": {
            "bgFrom": "#fbf5f7",
            "bgTo": "#f8f3ef",
            "panel": "rgba(255,255,255,.72)",
            "border": "rgba(190,18,60,.16)",
            "text": "#3a1d27",
            "accent": "#be123c"
          },
          "dark": {
            "bgFrom": "#1b0b12",
            "bgTo": "#2a1620",
            "panel": "rgba(244,63,94,.1)",
            "border": "rgba(251,113,133,.2)",
            "text": "#fff1f5",
            "accent": "#fda4af"
          }
        }
      },
      {
        "slot": "mint",
        "themeId": "waki-frost-mint",
        "name": "Mint",
        "description": "Calm green frost for finance, wellness, and notes.",
        "palette": {
          "light": {
            "bgFrom": "#f2faf5",
            "bgTo": "#eef8f6",
            "panel": "rgba(255,255,255,.72)",
            "border": "rgba(15,118,110,.18)",
            "text": "#0b3224",
            "accent": "#0f766e"
          },
          "dark": {
            "bgFrom": "#03170d",
            "bgTo": "#10261f",
            "panel": "rgba(34,197,94,.1)",
            "border": "rgba(134,239,172,.2)",
            "text": "#e9fff2",
            "accent": "#86efac"
          }
        }
      },
      {
        "slot": "violet",
        "themeId": "waki-frost-violet",
        "name": "Violet",
        "description": "Restrained violet frost for AI and knowledge work.",
        "palette": {
          "light": {
            "bgFrom": "#f5f3fb",
            "bgTo": "#f7f5fa",
            "panel": "rgba(255,255,255,.7)",
            "border": "rgba(109,40,217,.18)",
            "text": "#25163a",
            "accent": "#6d28d9"
          },
          "dark": {
            "bgFrom": "#10091f",
            "bgTo": "#241832",
            "panel": "rgba(109,40,217,.11)",
            "border": "rgba(196,181,253,.2)",
            "text": "#fbf1ff",
            "accent": "#c4b5fd"
          }
        }
      }
    ]
  },
  "academic": {
    "name": "Waki Academic",
    "description": "Clean research surfaces with restrained borders, modern typography, and calm knowledge-work color.",
    "structure": {
      "radius": 8,
      "blur": 0,
      "shadow": "research-hairline",
      "surface": "knowledge-panel",
      "iconography": "thin",
      "density": "spacious"
    },
    "variants": [
      {
        "slot": "ivory",
        "themeId": "waki-academic-ivory",
        "name": "Ivory",
        "description": "Clean ivory research surfaces with ink-blue accents.",
        "palette": {
          "light": {
            "bgFrom": "#f8fafc",
            "bgTo": "#f3f6fb",
            "panel": "#ffffff",
            "border": "#d3dce8",
            "text": "#111827",
            "accent": "#2563eb"
          },
          "dark": {
            "bgFrom": "#0e1420",
            "bgTo": "#182234",
            "panel": "#172033",
            "border": "#3b4b63",
            "text": "#f3f7fb",
            "accent": "#93c5fd"
          }
        }
      },
      {
        "slot": "oxford",
        "themeId": "waki-academic-oxford",
        "name": "Oxford",
        "description": "Deep blue knowledge-work surfaces for serious research tools.",
        "palette": {
          "light": {
            "bgFrom": "#f7fbff",
            "bgTo": "#edf4ff",
            "panel": "#ffffff",
            "border": "#bfcee5",
            "text": "#102033",
            "accent": "#1e40af"
          },
          "dark": {
            "bgFrom": "#07111f",
            "bgTo": "#0d1b31",
            "panel": "#111d31",
            "border": "#315076",
            "text": "#e7f0ff",
            "accent": "#93c5fd"
          }
        }
      },
      {
        "slot": "slate",
        "themeId": "waki-academic-slate",
        "name": "Slate",
        "description": "Cool gray reference surfaces for documentation and specs.",
        "palette": {
          "light": {
            "bgFrom": "#f8fafc",
            "bgTo": "#eef2f7",
            "panel": "#ffffff",
            "border": "#cbd5e1",
            "text": "#111827",
            "accent": "#475569"
          },
          "dark": {
            "bgFrom": "#111419",
            "bgTo": "#232a35",
            "panel": "#1d232d",
            "border": "#475569",
            "text": "#f3f7fb",
            "accent": "#cbd5e1"
          }
        }
      },
      {
        "slot": "sepia",
        "themeId": "waki-academic-sepia",
        "name": "Sepia",
        "description": "Warm neutral study mode with restrained amber accents.",
        "palette": {
          "light": {
            "bgFrom": "#faf8f5",
            "bgTo": "#f2eee8",
            "panel": "#ffffff",
            "border": "#d8d0c6",
            "text": "#27231d",
            "accent": "#a16207"
          },
          "dark": {
            "bgFrom": "#141312",
            "bgTo": "#25221e",
            "panel": "#211f1c",
            "border": "#5f574d",
            "text": "#f8f4ee",
            "accent": "#fbbf24"
          }
        }
      }
    ]
  },
  "desktop": {
    "name": "Waki Desktop",
    "description": "Dense native-app surfaces with compact controls, firm borders, and low-glare depth.",
    "structure": {
      "radius": 10,
      "blur": 12,
      "shadow": "compact-native",
      "surface": "solid-translucent",
      "iconography": "regular",
      "density": "compact"
    },
    "variants": [
      {
        "slot": "graphite",
        "themeId": "waki-desktop-graphite",
        "name": "Graphite",
        "description": "Graphite desktop chrome with electric blue focus.",
        "palette": {
          "light": {
            "bgFrom": "#f4f6f8",
            "bgTo": "#e8edf3",
            "panel": "rgba(255,255,255,.82)",
            "border": "rgba(71,85,105,.22)",
            "text": "#111827",
            "accent": "#2563eb"
          },
          "dark": {
            "bgFrom": "#111419",
            "bgTo": "#232a35",
            "panel": "rgba(45,52,64,.74)",
            "border": "rgba(125,211,252,.24)",
            "text": "#f3f7fb",
            "accent": "#38bdf8"
          }
        }
      },
      {
        "slot": "cobalt",
        "themeId": "waki-desktop-cobalt",
        "name": "Cobalt",
        "description": "Cobalt desktop shell for product and admin apps.",
        "palette": {
          "light": {
            "bgFrom": "#eef5ff",
            "bgTo": "#f8fbff",
            "panel": "rgba(255,255,255,.84)",
            "border": "rgba(59,130,246,.2)",
            "text": "#10213f",
            "accent": "#1d4ed8"
          },
          "dark": {
            "bgFrom": "#07111f",
            "bgTo": "#092a3f",
            "panel": "rgba(14,165,233,.12)",
            "border": "rgba(56,189,248,.27)",
            "text": "#e7f7ff",
            "accent": "#38bdf8"
          }
        }
      },
      {
        "slot": "nova",
        "themeId": "waki-desktop-nova",
        "name": "Nova",
        "description": "Violet command-center chrome with luminous accents.",
        "palette": {
          "light": {
            "bgFrom": "#f4f0ff",
            "bgTo": "#fff4fb",
            "panel": "rgba(255,255,255,.78)",
            "border": "rgba(147,51,234,.24)",
            "text": "#241239",
            "accent": "#9333ea"
          },
          "dark": {
            "bgFrom": "#10091f",
            "bgTo": "#2c1235",
            "panel": "rgba(147,51,234,.16)",
            "border": "rgba(244,114,182,.28)",
            "text": "#fbf1ff",
            "accent": "#d946ef"
          }
        }
      },
      {
        "slot": "olive",
        "themeId": "waki-desktop-olive",
        "name": "Olive",
        "description": "Muted green desktop shell for workbench and maker tools.",
        "palette": {
          "light": {
            "bgFrom": "#f4f7ed",
            "bgTo": "#eef5e8",
            "panel": "rgba(255,255,255,.82)",
            "border": "rgba(101,163,13,.22)",
            "text": "#1f2a12",
            "accent": "#4d7c0f"
          },
          "dark": {
            "bgFrom": "#0e1608",
            "bgTo": "#1b2912",
            "panel": "rgba(101,163,13,.14)",
            "border": "rgba(163,230,53,.24)",
            "text": "#efffd8",
            "accent": "#a3e635"
          }
        }
      }
    ]
  },
  "professional": {
    "name": "Waki Professional",
    "description": "Contemporary corporate surfaces with crisp hierarchy, restrained depth, and executive-grade colorways.",
    "structure": {
      "radius": 12,
      "blur": 8,
      "shadow": "executive-subtle",
      "surface": "crisp-translucent",
      "iconography": "regular",
      "density": "business"
    },
    "variants": [
      {
        "slot": "boardroom",
        "themeId": "waki-professional-boardroom",
        "name": "Boardroom",
        "description": "Navy, steel, and white for executive dashboards.",
        "palette": {
          "light": {
            "bgFrom": "#f6f8fb",
            "bgTo": "#edf2f7",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(71,85,105,.2)",
            "text": "#111827",
            "accent": "#1d4ed8"
          },
          "dark": {
            "bgFrom": "#0b1220",
            "bgTo": "#111827",
            "panel": "rgba(30,41,59,.78)",
            "border": "rgba(96,165,250,.24)",
            "text": "#f3f7fb",
            "accent": "#93c5fd"
          }
        }
      },
      {
        "slot": "meridian",
        "themeId": "waki-professional-meridian",
        "name": "Meridian",
        "description": "Blue-gray corporate SaaS surfaces with a clean cyan signal.",
        "palette": {
          "light": {
            "bgFrom": "#f7fbff",
            "bgTo": "#eef6fb",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(14,116,144,.18)",
            "text": "#0f2333",
            "accent": "#0369a1"
          },
          "dark": {
            "bgFrom": "#06131c",
            "bgTo": "#0c2430",
            "panel": "rgba(14,54,70,.78)",
            "border": "rgba(56,189,248,.24)",
            "text": "#e7f7ff",
            "accent": "#38bdf8"
          }
        }
      },
      {
        "slot": "sterling",
        "themeId": "waki-professional-sterling",
        "name": "Sterling",
        "description": "Neutral graphite with a discreet violet accent for premium tools.",
        "palette": {
          "light": {
            "bgFrom": "#f8f8fa",
            "bgTo": "#eff1f5",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(82,82,91,.18)",
            "text": "#18181b",
            "accent": "#6d28d9"
          },
          "dark": {
            "bgFrom": "#101014",
            "bgTo": "#1b1c22",
            "panel": "rgba(39,39,46,.78)",
            "border": "rgba(167,139,250,.24)",
            "text": "#f4f4f5",
            "accent": "#a78bfa"
          }
        }
      },
      {
        "slot": "capital",
        "themeId": "waki-professional-capital",
        "name": "Capital",
        "description": "Slate and deep green for finance, ops, and business intelligence.",
        "palette": {
          "light": {
            "bgFrom": "#f7faf8",
            "bgTo": "#edf5f0",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(5,150,105,.2)",
            "text": "#10231b",
            "accent": "#047857"
          },
          "dark": {
            "bgFrom": "#07150f",
            "bgTo": "#10231a",
            "panel": "rgba(13,54,37,.78)",
            "border": "rgba(52,211,153,.24)",
            "text": "#ecfdf5",
            "accent": "#34d399"
          }
        }
      }
    ]
  },
  "corporate": {
    "name": "Waki Corporate",
    "description": "Enterprise-grade product surfaces: measured contrast, exact spacing, solid panels, and conservative executive polish.",
    "structure": {
      "radius": 8,
      "blur": 0,
      "shadow": "corporate-layer",
      "surface": "solid-enterprise",
      "iconography": "regular",
      "density": "efficient"
    },
    "variants": [
      {
        "slot": "atlas",
        "themeId": "waki-corporate-atlas",
        "name": "Atlas",
        "description": "Global enterprise blue-gray for serious SaaS products.",
        "palette": {
          "light": {
            "bgFrom": "#f8fafc",
            "bgTo": "#eef2f6",
            "panel": "#ffffff",
            "border": "#cbd5e1",
            "text": "#111827",
            "accent": "#1d4ed8"
          },
          "dark": {
            "bgFrom": "#0f172a",
            "bgTo": "#172033",
            "panel": "#1e293b",
            "border": "#475569",
            "text": "#f8fafc",
            "accent": "#93c5fd"
          }
        }
      },
      {
        "slot": "ledger",
        "themeId": "waki-corporate-ledger",
        "name": "Ledger",
        "description": "Graphite and green for finance, accounting, and BI.",
        "palette": {
          "light": {
            "bgFrom": "#f8faf9",
            "bgTo": "#eef4f1",
            "panel": "#ffffff",
            "border": "#cbd8d1",
            "text": "#10231b",
            "accent": "#047857"
          },
          "dark": {
            "bgFrom": "#0b1511",
            "bgTo": "#14231d",
            "panel": "#1a2b24",
            "border": "#3f5f50",
            "text": "#ecfdf5",
            "accent": "#34d399"
          }
        }
      },
      {
        "slot": "summit",
        "themeId": "waki-corporate-summit",
        "name": "Summit",
        "description": "Warm charcoal and restrained amber for leadership tools.",
        "palette": {
          "light": {
            "bgFrom": "#faf9f7",
            "bgTo": "#f0ede8",
            "panel": "#ffffff",
            "border": "#d6d3d1",
            "text": "#1c1917",
            "accent": "#b45309"
          },
          "dark": {
            "bgFrom": "#171412",
            "bgTo": "#28231f",
            "panel": "#292524",
            "border": "#57534e",
            "text": "#fafaf9",
            "accent": "#fbbf24"
          }
        }
      },
      {
        "slot": "harbor",
        "themeId": "waki-corporate-harbor",
        "name": "Harbor",
        "description": "Steel blue and slate for operational platforms.",
        "palette": {
          "light": {
            "bgFrom": "#f7fbfd",
            "bgTo": "#edf5f8",
            "panel": "#ffffff",
            "border": "#c6d8de",
            "text": "#102a33",
            "accent": "#0f766e"
          },
          "dark": {
            "bgFrom": "#07151a",
            "bgTo": "#102630",
            "panel": "#17313a",
            "border": "#35616d",
            "text": "#e7fbff",
            "accent": "#5eead4"
          }
        }
      }
    ]
  },
  "frosted-pro": {
    "name": "Waki Frosted Pro",
    "description": "Professional frosted glass with restrained sheen, premium shadows, and a polished boardroom feel.",
    "structure": {
      "radius": 12,
      "blur": 28,
      "shadow": "professional-frost",
      "surface": "frosted-executive",
      "iconography": "regular",
      "density": "business"
    },
    "variants": [
      {
        "slot": "platinum",
        "themeId": "waki-frosted-pro-platinum",
        "name": "Platinum",
        "description": "Silver frost with blue executive accents.",
        "palette": {
          "light": {
            "bgFrom": "#f6f8fb",
            "bgTo": "#eef3f8",
            "panel": "rgba(255,255,255,.68)",
            "border": "rgba(148,163,184,.24)",
            "text": "#111827",
            "accent": "#2563eb"
          },
          "dark": {
            "bgFrom": "#0d121c",
            "bgTo": "#1a2330",
            "panel": "rgba(51,65,85,.66)",
            "border": "rgba(147,197,253,.24)",
            "text": "#f4f8fc",
            "accent": "#93c5fd"
          }
        }
      },
      {
        "slot": "azure",
        "themeId": "waki-frosted-pro-azure",
        "name": "Azure",
        "description": "Crisp blue frosted glass for professional SaaS.",
        "palette": {
          "light": {
            "bgFrom": "#f0f7fc",
            "bgTo": "#f7fbff",
            "panel": "rgba(255,255,255,.7)",
            "border": "rgba(14,116,144,.18)",
            "text": "#0c2233",
            "accent": "#0369a1"
          },
          "dark": {
            "bgFrom": "#07131f",
            "bgTo": "#102338",
            "panel": "rgba(14,55,82,.62)",
            "border": "rgba(125,211,252,.2)",
            "text": "#e7f7ff",
            "accent": "#7dd3fc"
          }
        }
      },
      {
        "slot": "jade",
        "themeId": "waki-frosted-pro-jade",
        "name": "Jade",
        "description": "Green-tinted executive frost for finance and ops.",
        "palette": {
          "light": {
            "bgFrom": "#f0fbf6",
            "bgTo": "#f8fffb",
            "panel": "rgba(255,255,255,.68)",
            "border": "rgba(16,185,129,.22)",
            "text": "#0d2b20",
            "accent": "#059669"
          },
          "dark": {
            "bgFrom": "#071711",
            "bgTo": "#102a20",
            "panel": "rgba(16,74,53,.66)",
            "border": "rgba(52,211,153,.24)",
            "text": "#ecfdf5",
            "accent": "#34d399"
          }
        }
      },
      {
        "slot": "amethyst",
        "themeId": "waki-frosted-pro-amethyst",
        "name": "Amethyst",
        "description": "Subtle violet frost for premium internal tools.",
        "palette": {
          "light": {
            "bgFrom": "#f6f4fb",
            "bgTo": "#fbfaff",
            "panel": "rgba(255,255,255,.7)",
            "border": "rgba(109,40,217,.16)",
            "text": "#21163a",
            "accent": "#6d28d9"
          },
          "dark": {
            "bgFrom": "#120e1f",
            "bgTo": "#211b31",
            "panel": "rgba(55,48,82,.62)",
            "border": "rgba(196,181,253,.2)",
            "text": "#f5f3ff",
            "accent": "#c4b5fd"
          }
        }
      }
    ]
  },
  "system": {
    "name": "System",
    "description": "Native-inspired desktop themes that echo current macOS and Windows app conventions.",
    "structure": {
      "radius": 10,
      "blur": 14,
      "shadow": "native-window",
      "surface": "system-material",
      "iconography": "regular",
      "density": "desktop"
    },
    "variants": [
      {
        "slot": "mac",
        "themeId": "waki-system-mac",
        "name": "Mac",
        "description": "macOS-style sidebar translucency, unified toolbar, system blue, and soft window depth.",
        "palette": {
          "light": {
            "bgFrom": "#f5f5f7",
            "bgTo": "#eceef2",
            "panel": "rgba(255,255,255,.66)",
            "border": "rgba(60,60,67,.18)",
            "text": "#1d1d1f",
            "accent": "#007aff"
          },
          "dark": {
            "bgFrom": "#1c1c1e",
            "bgTo": "#2c2c2e",
            "panel": "rgba(58,58,60,.62)",
            "border": "rgba(99,99,102,.35)",
            "text": "#f5f5f7",
            "accent": "#0a84ff"
          }
        }
      },
      {
        "slot": "windows",
        "themeId": "waki-system-windows",
        "name": "Windows",
        "description": "Windows 11-style Mica/Acrylic feel with Segoe UI, rounded command surfaces, and Fluent blue.",
        "palette": {
          "light": {
            "bgFrom": "#f3f6fb",
            "bgTo": "#eef3f8",
            "panel": "rgba(255,255,255,.78)",
            "border": "rgba(120,120,120,.2)",
            "text": "#1a1a1a",
            "accent": "#0067c0"
          },
          "dark": {
            "bgFrom": "#202020",
            "bgTo": "#1b1b1b",
            "panel": "rgba(45,45,45,.82)",
            "border": "rgba(117,117,117,.28)",
            "text": "#f3f3f3",
            "accent": "#60cdff"
          }
        }
      }
    ]
  },
  "mobile": {
    "name": "Waki Mobile",
    "description": "Polished touch surfaces with clear hierarchy for professional mobile apps.",
    "structure": {
      "radius": 20,
      "blur": 24,
      "shadow": "soft-touch",
      "surface": "rounded-glass",
      "iconography": "regular",
      "density": "touch"
    },
    "variants": [
      {
        "slot": "orchid",
        "themeId": "waki-mobile-orchid",
        "name": "Plum",
        "description": "Muted plum mobile surfaces for premium productivity apps.",
        "palette": {
          "light": {
            "bgFrom": "#f7f6fa",
            "bgTo": "#f2f4f8",
            "panel": "rgba(255,255,255,.76)",
            "border": "rgba(91,63,122,.16)",
            "text": "#2c2434",
            "accent": "#5b3f7a"
          },
          "dark": {
            "bgFrom": "#15121b",
            "bgTo": "#221c2d",
            "panel": "rgba(91,63,122,.12)",
            "border": "rgba(185,167,210,.18)",
            "text": "#f6f0ff",
            "accent": "#b9a7d2"
          }
        }
      },
      {
        "slot": "mint",
        "themeId": "waki-mobile-mint",
        "name": "Mint",
        "description": "Professional green mobile theme with readable dark mode.",
        "palette": {
          "light": {
            "bgFrom": "#f2faf5",
            "bgTo": "#eef8f6",
            "panel": "rgba(255,255,255,.74)",
            "border": "rgba(15,118,110,.18)",
            "text": "#0b3224",
            "accent": "#0f766e"
          },
          "dark": {
            "bgFrom": "#03170d",
            "bgTo": "#10261f",
            "panel": "rgba(34,197,94,.1)",
            "border": "rgba(134,239,172,.2)",
            "text": "#e9fff2",
            "accent": "#86efac"
          }
        }
      },
      {
        "slot": "sunrise",
        "themeId": "waki-mobile-sunrise",
        "name": "Sunrise",
        "description": "Warm neutral mobile surfaces for planning and service apps.",
        "palette": {
          "light": {
            "bgFrom": "#faf7f2",
            "bgTo": "#f8f3ef",
            "panel": "rgba(255,255,255,.78)",
            "border": "rgba(180,83,9,.18)",
            "text": "#3a2515",
            "accent": "#b45309"
          },
          "dark": {
            "bgFrom": "#17120e",
            "bgTo": "#2a211b",
            "panel": "rgba(251,146,60,.1)",
            "border": "rgba(253,186,116,.2)",
            "text": "#fff2df",
            "accent": "#fdba74"
          }
        }
      },
      {
        "slot": "ocean",
        "themeId": "waki-mobile-ocean",
        "name": "Ocean",
        "description": "Blue-green touch surfaces for field and logistics apps.",
        "palette": {
          "light": {
            "bgFrom": "#f0f8fb",
            "bgTo": "#eef8f6",
            "panel": "rgba(255,255,255,.74)",
            "border": "rgba(14,116,144,.18)",
            "text": "#073349",
            "accent": "#0369a1"
          },
          "dark": {
            "bgFrom": "#031923",
            "bgTo": "#082d3a",
            "panel": "rgba(14,165,233,.1)",
            "border": "rgba(125,211,252,.2)",
            "text": "#e5fbff",
            "accent": "#7dd3fc"
          }
        }
      }
    ]
  },
  "command": {
    "name": "Waki Command",
    "description": "Sharp technical surfaces with restrained signal color and terminal-like focus.",
    "structure": {
      "radius": 8,
      "blur": 6,
      "shadow": "signal-glow",
      "surface": "dark-tooling",
      "iconography": "regular",
      "density": "compact"
    },
    "variants": [
      {
        "slot": "cyan",
        "themeId": "waki-command-cyan",
        "name": "Cyan",
        "description": "Blue command surfaces for developer tools.",
        "palette": {
          "light": {
            "bgFrom": "#f8fbfd",
            "bgTo": "#eef6fa",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(14,116,144,.18)",
            "text": "#0b2330",
            "accent": "#0e7490"
          },
          "dark": {
            "bgFrom": "#041014",
            "bgTo": "#071820",
            "panel": "rgba(6,182,212,.08)",
            "border": "#164e63",
            "text": "#dffaff",
            "accent": "#67e8f9"
          }
        }
      },
      {
        "slot": "lime",
        "themeId": "waki-command-lime",
        "name": "Lime",
        "description": "Olive signal tools for monitoring and automation.",
        "palette": {
          "light": {
            "bgFrom": "#fafcf7",
            "bgTo": "#f3f7ed",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(101,163,13,.18)",
            "text": "#1d2b0f",
            "accent": "#4d7c0f"
          },
          "dark": {
            "bgFrom": "#0c1404",
            "bgTo": "#121d08",
            "panel": "rgba(132,204,22,.08)",
            "border": "#3f6212",
            "text": "#ecfccb",
            "accent": "#bef264"
          }
        }
      },
      {
        "slot": "magenta",
        "themeId": "waki-command-magenta",
        "name": "Burgundy",
        "description": "Restrained burgundy command surfaces for technical creative apps.",
        "palette": {
          "light": {
            "bgFrom": "#faf7f8",
            "bgTo": "#f5f2f4",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(127,29,29,.18)",
            "text": "#2f171a",
            "accent": "#7f1d1d"
          },
          "dark": {
            "bgFrom": "#150b0d",
            "bgTo": "#211113",
            "panel": "rgba(127,29,29,.1)",
            "border": "#7f1d1d",
            "text": "#fee2e2",
            "accent": "#fca5a5"
          }
        }
      },
      {
        "slot": "amber",
        "themeId": "waki-command-amber",
        "name": "Amber",
        "description": "Restrained amber terminal warmth for ops tools.",
        "palette": {
          "light": {
            "bgFrom": "#faf7f0",
            "bgTo": "#f7f2ea",
            "panel": "rgba(255,255,255,.86)",
            "border": "rgba(180,83,9,.18)",
            "text": "#351c09",
            "accent": "#b45309"
          },
          "dark": {
            "bgFrom": "#190b05",
            "bgTo": "#24130a",
            "panel": "rgba(249,115,22,.08)",
            "border": "#7c2d12",
            "text": "#ffedd5",
            "accent": "#fdba74"
          }
        }
      }
    ]
  }
};

export const VARIANT_BY_THEME_ID = (() => {
  const out = {};
  for (const [familyId, family] of Object.entries(FAMILIES)) {
    for (const variant of family.variants) {
      out[variant.themeId] = {
        familyId,
        familyName: family.name,
        slot: variant.slot,
        variantName: variant.name,
      };
    }
  }
  return out;
})();
